name: MGConquer
main: com.comze_instancelabs.conquer.Main
version: 1.0.0
author: InstanceLabs
softdepend: [Vault, MinigamesAPI]
depend: [MinigamesAPI]
loadbefore: [MinigamesAPI]
commands:
   cq:
      description: Main command
      usage: /cq [action]
      aliases: [conquer, mgconquer]
