name: MGConquer
main: com.comze_instancelabs.conquer.Main
version: 1.3.1
author: InstanceLabs
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   cq:
      description: Main command
      usage: /cq [action]
      aliases: [conquer, mgconquer]
