name: MGConquer
main: com.comze_instancelabs.conquer.Main
version: ${version}
author: [InstanceLabs,mepeisen]
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   cq:
      description: Main command
      usage: /cq [action]
      aliases: [conquer, mgconquer]
